var frases = [
    'Pray tomorrow gets me higher\nHigher\nHigher\nPressure on people, people on streets... 🎵🎶',
    'Mama, just killed a man\nPut a gun against his head\nPulled my trigger, now he’s dead\nMama, life had just begun\nBut now I’ve gone and thrown it all away... 🎵🎶',
    'Mama! Ooh!\nDidn’t mean to make you cry\nIf I’m not back again this time tomorrow\nCarry on, carry on\nAs if nothing really matters... 🎵🎶',
    'Easy come, easy go\nWill you let me go?... 🎵🎶',
    'Anyway, the wind blows, doesn’t really matter to me... 🎵🎶',
    'Open your eyes, look up to the skies and see... 🎵🎶',
    'Gotta leave you all behind and face the truth... 🎵🎶',
    'Love of my life, don’t leave me, you’ve stolen my love and now desert me... 🎵🎶',
    'When I grow older, I will be there at your side to remind you how I still love you... 🎵🎶',
    'You will remember when this is blown over and everything’s all by the way... 🎵🎶',
    'We are the champions, my friends, and we’ll keep on fighting till the end... 🎵🎶',
    'You brought me fame and fortune and everything that goes with it... 🎵🎶',
    'I’ve paid my dues time after time, I’ve done my sentence but committed no crime... 🎵🎶',
    'I want to break free from your lies, you’re so self satisfied I don’t need you... 🎵🎶',
    'I’ve fallen in love for the first time and this time I know it’s for real... 🎵🎶',
    'It’s strange but it’s true I can’t get over the way you love me like you do... 🎵🎶',
    'When all the salt is taken from the sea I stand dethroned, I’m naked and I bleed... 🎵🎶',
    'I was born to love you with every single beat of my heart... 🎵🎶',
    'I was born to take care of you every single day of my life... 🎵🎶',
    'Pressure, pushing down on me\nPressing down on you\nNo man ask for... 🎵🎶',
    'It’s the terror of knowing\nWhat this world is about\nWatching some good friends\nScreaming: Let me out\nPray tomorrow gets me higher\nPressure on people, people on streets... 🎵🎶',
    'Galileo! Galileo!\nGalileo! Galileo!\nGalileo, Figaro!\nMagnifico!... 🎵🎶',
    'I’m just a poor boy and nobody loves me\nHe’s just a poor boy from a poor family\nSpare him his life, from this monstrosity... 🎵🎶',
    'Mama! Ooh!\nI don’t wanna die\nI sometimes wish I’d never been born at all... 🎵🎶',
    'I’d sit alone and watch your light\nMy only friend through teenage nights\nAnd everything I had to know\nI heard it on my radio... 🎵🎶',
    'You gave them all those old time stars\nThrough wars of worlds invaded by Mars\nYou’ve made ’em laugh, you’ve made ’em cry\nYou’ve made us feel like we could fly... 🎵🎶',
    'So, don’t become some background noise\nA backdrop for the girls and boys\nWho just don’t know or just don’t care\nAnd just complain when you’re not there... 🎵🎶',
    'You’ve had your time, you’ve had the power\nYou’ve yet to have your finest hour\nRadio... 🎵🎶',
    'We watch the shows, we watch the stars\nOn videos for hours and hours\nWe hardly need to use our ears\nHow music changes through the years... 🎵🎶',
    'All we hear is Radio Ga Ga\nRadio Goo Goo\nRadio Ga Ga... 🎵🎶',
    'All we hear is Radio Ga Ga\nRadio Blah Blah\nRadio, what’s new?\nSomeone still loves you... 🎵🎶',
    'Caviar and cigarettes\nWell versed in etiquette\nExtraordinarily nice... 🎵🎶',
    'She’s a Killer Queen... 🎵🎶',
    'She’s a Killer Queen\nGunpowder, gelatine\nDynamite with a laser beam\nGuaranteed to blow your mind\nAnytime... 🎵🎶',
    'Recommended at the price\nInsatiable in appetite\nWanna try?... 🎵🎶',
    'Wanna try?... 🎵🎶',
    'To avoid complications\nShe never kept the same address... 🎵🎶',
    'Then again incidentally\nIf you’re that way inclined... 🎵🎶',
    'Perfume came naturally from Paris (naturally)\nFor cars she couldn’t care less\nFastidious and precise... 🎵🎶',
    'You wanna try!... 🎵🎶',
    'I can dim the lights and sing you songs full of sad things\nWe can do the tango just for two... 🎵🎶',
    'I can serenade and gently play on your heart strings\nBe your valentino just for you... 🎵🎶',
    'Oh love, oh lover boy\nWhat’re doing tonight, hey, boy?... 🎵🎶',
    'Set my alarm, turn on my charm\nThat’s because I’m a good old fashioned lover boy... 🎵🎶',
    'Oh let me feel you heartbeat (grow faster faster)\nOh can you feel my love heat... 🎵🎶',
    'Come on and sit on my hot seat of love\nAnd tell me how do you feel right after all... 🎵🎶',
    'I’d like for you and I to go romancing\nSay the word, your wish is my command... 🎵🎶',
    'When I’m not with you\nThink of me always, I love you love you... 🎵🎶',
    'This thing called love\nI just can’t handle it... 🎵🎶',
    'I ain’t ready\nCrazy little thing called love... 🎵🎶',
    'There goes my baby\nShe knows how to rock’n’roll\nShe drives me crazy... 🎵🎶',
    'She gives me hot and cold fever\nShe leaves me in a cool cool sweat... 🎵🎶',
    'Crazy little thing called love, yeah, yeah... 🎵🎶',
    'There’s no time for us\nThere’s no place for us... 🎵🎶',
    'Who wants to live forever?... 🎵🎶',
    'There’s no chance for us\nIt’s all decided for us... 🎵🎶',
    'But touch my tears with your lips\nTouch my world with your fingertips\nAnd we can have forever... 🎵🎶',
    'I was born to love you\nWith every single beat of my heart... 🎵🎶',
    'So take a chance with me\nLet me romance with you... 🎵🎶',
    'Another red letter day\nSo the pound has dropped\nAnd the children are creating... 🎵🎶',
    'Friends will be friends\nWhen you’re in need of love\nThey give care and attention... 🎵🎶',
    'When you’re through with life\nAnd all hope is lost\nHold out your hand\n’Cause friends will be friends\night to the end... 🎵🎶',
    'It’s so easy now\n’Cause you got friends you can trust... 🎵🎶',
    'It’s a kind of magic... 🎵🎶',
    'One dream, one soul, one prize, one goal\nOne golden glance of what should be... 🎵🎶',
    'One shaft of light that shows the way\nNo mortal man can win this day... 🎵🎶',
    'The waiting seems eternity\nThe day will dawn of sanity... 🎵🎶',
    'Is this a kind of magic?\nIt’s a kind of magic\nThere can be only one... 🎵🎶',
    'This flame that burns inside of me\nI’m hearing secret harmonies\nIt’s a kind of magic... 🎵🎶',
    'Ooh, you make me live... 🎵🎶',
    'Ooh, you’re the best friend that I ever had... 🎵🎶',
    'I really love you... 🎵🎶',
    'Empty spaces\nWhat are we living for?... 🎵🎶',
    'Abandoned places\nI guess we know the score... 🎵🎶',
    'Does anybody know what we are looking for?... 🎵🎶',
    'Another hero\nAnother mindless crime... 🎵🎶',
    'Behind the curtain\nIn the pantomime\nHold the line... 🎵🎶',
    'Does anybody want to take it anymore?... 🎵🎶',
    'The show must go on... 🎵🎶',
    'Inside my heart is breaking\nMy make up may be flaking\nBut my smile\nStill stays on... 🎵🎶',
    'Whatever happens\nI’ll leave it all to chance... 🎵🎶',
    'Another heartache\nAnother failed romance... 🎵🎶',
    'My soul is painted like the wings of butterflies... 🎵🎶',
    'I can fly, my friends... 🎵🎶',
    'Steve walks warily down the street\nWith his brim pulled way down low... 🎵🎶',
    'Ain’t no sound but the sound of his feet\nMachine guns ready to go... 🎵🎶',
    'Are you ready, hey, are you ready for this?... 🎵🎶',
    'Are you hanging on the edge of your seat?... 🎵🎶',
    'Out of the doorway the bullets rip\nTo the sound of the beat, yeah... 🎵🎶',
    'Another one bites the dust... 🎵🎶',
    'And another one gone, and another one gone... 🎵🎶',
    'Hey, I’m gonna get you too\nAnother one bites the dust... 🎵🎶',
    'How do you think I’m going to get along\nWithout you when you’re gone... 🎵🎶',
    'You took me for everything that I had\nAnd kicked me out on my own... 🎵🎶',
    'Are you happy, are you satisfied?\nHow long can you stand the heat?... 🎵🎶',
    'Can anybody find me somebody to love?... 🎵🎶',
    'Each morning I get up I die a little... 🎵🎶',
    'Can barely stand on my feet... 🎵🎶',
    'Lord, what you’re doing to me?... 🎵🎶',
    'I have spent all my years in believing you... 🎵🎶',
    'Find me somebody to love, find me somebody to love... 🎵🎶',
    'Somebody, find me somebody to love\nCan anybody find me somebody to love?... 🎵🎶',
    'All dead, all dead\nAll the dreams we had\nAnd I wonder why I still live on... 🎵🎶',
    'All dead, all dead... 🎵🎶',
    'The minute you walked in the joint\nI could see you were a man of distinction... 🎵🎶',
    'Hey, big spender\nSpend a little time with me... 🎵🎶',
    'You suck my blood like a leech... 🎵🎶',
    'You break the law and you breach... 🎵🎶',
    'Screw my brain till it hurts\nYou’ve taken all my money and you want more... 🎵🎶',
    'Misguided old mule\nWith your pig headed rules\nWith your narrow minded cronies\nWho are fools of the first division... 🎵🎶',
    'Death on two legs\nYou’re tearing me apart... 🎵🎶',
    'Death on two legs\nYou’ve never had a heart of your own... 🎵🎶',
    'You’re just an old barrow boy\nHave you found a new toy\nTo replace me?... 🎵🎶',
    'But now you can kiss\nMy ass goodbye... 🎵🎶',
    'Yesterday my life was in ruin\nNow today I know what I’m doing... 🎵🎶',
    'Got a feeling I should be doing all right\nDoing all right... 🎵🎶',
    'Tonight I’m gonna have myself a real good time... 🎵🎶',
    'And the world, I’ll turn it inside out, yeah!... 🎵🎶',
    'I’m floating around in ecstasy... 🎵🎶',
    'So don’t stop me now... 🎵🎶',
    'Don’t stop me\n’Cause I’m having a good time, having a good time... 🎵🎶',
    'I’m a shooting star leaping through the sky\nLike a tiger defying the laws of gravity... 🎵🎶',
    'I’m a racing car passing by, like Lady Godiva\nI’m gonna go, go, go\nThere’s no stopping me... 🎵🎶',
    'I’m burning through the sky, yeah!\nTwo hundred degrees\nThat’s why they call me Mister Fahrenheit... 🎵🎶',
    'I’m travelling at the speed of light\nI wanna make a supersonic man out of you... 🎵🎶',
    'Don’t stop me now\nI’m having such a good time\nI’m having a ball... 🎵🎶',
    'If you wanna have a good time, just give me a call... 🎵🎶',
    'I’m a rocket ship on my way to Mars\nOn a collision course... 🎵🎶',
    'I am a sex machine ready to reload... 🎵🎶',
    'Are you gonna take me home tonight?... 🎵🎶',
    'Fat bottomed girls\nYou make the rockin’ world go round... 🎵🎶',
    'I was just a skinny lad\nNever knew no good from bad\nBut I knew life before I left my nursery... 🎵🎶',
    'Left alone with big fat Fanny\nShe was such a naughty nanny\nHey, big woman, you made a bad boy out of me... 🎵🎶',
    'I’ve been singing with my band\nAcross the water, across the land',
    'Oh, won’t you take me home tonight?... 🎵🎶',
    'Here we stand or here we fall\nHistory won’t care at all... 🎵🎶',
    'Oh, every night and every day\nA little piece of you is falling away... 🎵🎶',
    'You know it’s time for the hammer to fall... 🎵🎶',
    'I think I’m a banana tree\nOh, dear... 🎵🎶',
    'I’m going slightly mad... 🎵🎶',
    'I live my life for you\nThink all my thoughts with you and only you',
    'Anything you ask I do for you... 🎵🎶',
    'I touch your lips with mine\nBut in the end I leave it to the lords... 🎵🎶',
    'Leave it in the lap of the gods... 🎵🎶',
    'It’s so easy but I can’t do it\nSo risky\nBut I gotta chance it... 🎵🎶',
    'It’s so funny\nThere’s nothing to laugh about... 🎵🎶',
    'My money\nThat’s all you want to talk about... 🎵🎶',
    'I can see what you want me to be\nBut I’m not fool... 🎵🎶',
    'No beginning there’s no ending\nThere’s no meaning... 🎵🎶',
    'I can’t set you free from me\nBut that’s not true... 🎵🎶',
    'If there’s a God or any kind of justice under the sky... 🎵🎶',
    'Just look at all those hungry mouths we have to feed\nTake a look at all the suffering we breed\nSo many lonely faces scattered all around\nSearching for what they need... 🎵🎶',
    'Is this the world we created?\nWhat did we do it for?... 🎵🎶',
    'If there’s a God in the sky looking down\nWhat must he think of what we’ve done\nTo the world that he created?... 🎵🎶',
    'You know that every day a helpless child is born\nWho needs some loving care inside a happy home\nSomewhere a wealthy man is sitting on his throne\nWaiting for life to go by... 🎵🎶',
    'There’s no reason for living\nWith a broken heart... 🎵🎶',
    'You win, you lose\nIt’s a chance you have to take with love... 🎵🎶',
    'But now you say it’s over and I’m falling apart... 🎵🎶',
    'It’s a hard life\nTo be true lovers together\nTo love and live forever\nIn each others hearts... 🎵🎶',
    'It’s a long hard fight\nTo learn to care for each other\nTo trust in one another\nRight from the start... 🎵🎶',
    'It’s a hard life... 🎵🎶',
    'I was told a million times\nOf all the troubles in my way\nMight to grow a little wiser\nLittle better ev’ry day... 🎵🎶',
    'But if I crossed a million rivers\nAnd I rode a million miles\nThen I’d still be where I started\nBread and butter for a smile... 🎵🎶',
    'Keep yourself alive... 🎵🎶',
    'Las palabras de amor\nLet me hear the words of love\nDespacito mi amor\nLove me slow and gently... 🎵🎶',
    'I have sinned dear father, father, I have sinned... 🎵🎶',
    'Nobody believes me... 🎵🎶',
    'Sire I have stolen, stolen many times... 🎵🎶',
    'Liar, I have sailed the seas... 🎵🎶',
    'Liar, from Mars to Mercury... 🎵🎶',
    'Liar, you’re lying to me... 🎵🎶',
    'Mama I’m gonna be your slave\nAll day long',
    'Love of my life, you’ve hurt me\nYou’ve broken my heart\nAnd now you leave me... 🎵🎶',
    'Love of my life, can’t you see?\nBring it back, bring it back... 🎵🎶',
    'Don’t take it away from me\nBecause you don’t know\nWhat it means to me... 🎵🎶',
    'Love of my life, don’t leave me\nYou’ve taken my love \nAnd now desert me... 🎵🎶',
    'You will remember \nWhen this is blown over... 🎵🎶',
    'When I grow older\nI will be there at your side\nTo remind you how I still love you\nI still love you... 🎵🎶',
    'I still love you... 🎵🎶',
    'In the land where horses born with eagle wings... 🎵🎶',
    'My fairy king... 🎵🎶',
    'Mother Mercury (Mercury)\nLook what they’ve done to me\nI cannot run, I cannot hide... 🎵🎶',
    'Another party’s over\nAnd I’m left cold sober\nMy baby left me for somebody new... 🎵🎶',
    'I don’t wanna talk about it\nWant to forget about it\nWanna be intoxicated with that special brew... 🎵🎶',
    'So come and get me\nLet me\nGet in that sinking feeling... 🎵🎶',
    'One man, one goal, one mission... 🎵🎶',
    'One heart, one soul, just one solution... 🎵🎶',
    'One flash of light, yeah, one God, one vision... 🎵🎶',
    'I had a dream\nWhen I was young\nA dream of sweet illusion\nA glimpse of hope and unity\nAnd visions of one sweet union... 🎵🎶',
    'Open up your mind and let me step inside... 🎵🎶',
    'Play the game\nEverybody play the game of love... 🎵🎶',
    'It started off so well\nThey said we made a perfect pair... 🎵🎶',
    'Save me, save me, save me\nI can’t face this life alone... 🎵🎶',
    'Fear me, you lord and lady preachers\nI descend upon your Earth from the skies... 🎵🎶',
    'Bring before me what is mine!\nThe seven seas of Rhye... 🎵🎶',
    'Can you hear me, you peers and privy councillors?... 🎵🎶',
    'I stand before you naked to the eyes... 🎵🎶',
    'You are mine! I possess you!\nBelong to you\nForever!... 🎵🎶',
    'Storm the master marathon I’ll fly through\nBy flash and thunder fire, I’ll survive... 🎵🎶',
    'I’ll take you to the seven seas of Rhye... 🎵🎶',
    'Oh yes I’m the great pretender... 🎵🎶',
    'Give a little love to me\nTake a little love from me\nI want to share it with you\nI feel like a millionaire... 🎵🎶',
    'I reign with my left hand, I rule with my right... 🎵🎶',
    'I’m lord of all darkness, I’m queen of the night... 🎵🎶',
    'Now do the march of the Black Queen... 🎵🎶',
    'Sometimes I get to feeling\nI was back in the old days, long ago... 🎵🎶',
    'When we were kids, when we were young\nThing seemed so perfect, you know... 🎵🎶',
    'The days were endless, we were crazy, we were young\nThe Sun was always shining, we just lived for fun... 🎵🎶',
    'Sometimes it seems like lately I just don’t know\nThe rest of my life’s been just a show... 🎵🎶',
    'Those were the days of our lives\nThe bad things in life were so few... 🎵🎶',
    'Those days are all gone now, but one thing is true\nWhen I look and I find I still love you... 🎵🎶',
    'You can’t turn back the clock, you can’t turn back the tide\nAin’t that a shame?... 🎵🎶',
    'When I look and I find\nI still love you',
    'I’m just the pieces of the man I used to be... 🎵🎶',
    'Too many bitter tears are raining down on me... 🎵🎶',
    'Oh, I feel like no-one ever told the truth to me... 🎵🎶',
    'Too much love will kill you\nIf you can’t make up your mind... 🎵🎶',
    'Torn between the lover and the love you leave behind... 🎵🎶',
    'Too much love will kill you every time... 🎵🎶',
    'I’m just the shadow of the man I used to be\nAnd it seems like there’s no way out of this for me... 🎵🎶',
    'I used to bring you sunshine\nNow all I ever do is bring you down, oooh... 🎵🎶',
    'Too much love will kill you\nJust as sure as none at all... 🎵🎶',
    'Yeah too much love will kill you\nItvll make your life a lie... 🎵🎶',
    'Look into my eyes and you’ll see I’m the only one... 🎵🎶',
    'You’ve captured my love stolen my heart\nChanged my life... 🎵🎶',
    'Every time you make a move you destroy my mind... 🎵🎶',
    'And the way you touch\nI lose control and shiver deep inside... 🎵🎶',
    'You take my breath away... 🎵🎶',
    'You can reduce me to tears with a single sigh... 🎵🎶',
    'Ev’ry breath that you take\nAny sound that you make is a whisper in my ear... 🎵🎶',
    'I could give up all my life for just one kiss... 🎵🎶',
    'I would surely die if you dismiss me from your love... 🎵🎶',
    'So, please, don’t go\nDon’t leave me here all by myself... 🎵🎶',
    'I get ever so lonely from time to time... 🎵🎶',
    'I will find you anywhere you go\nI’ll be right behind you\nRight until the ends of the earth... 🎵🎶',
    'I’ll get no sleep until I find you\nTo tell you that you just take my breath away... 🎵🎶',
    'I will find you anywhere you go\nRight until the ends of the earth... 🎵🎶',
    'I’ll get no sleep until I find you\nTo tell you when I’ve found you\nI love you... 🎵🎶'
]

module.exports = frases